# Generated by Django 3.0.8 on 2020-09-29 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='This is not a valid first name.', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='This is not a valid last name.', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")])),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('git_username', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_user_name', message='This is not a valid first username.', regex='^[aA-zZ]\\\\w{5, 29}$')])),
                ('university', models.CharField(choices=[('', 'Select Your University'), ('USTHB', 'USTHB'), ('ENP', 'ENP'), ('ENSTP', 'ENSTP'), ('ESI', 'ESI'), ('ESSA', 'ESSA'), ('O', 'Other')], max_length=5)),
                ('branch', models.CharField(choices=[('', 'Select Your Branch'), ('MI', 'Mathematics and Computer Science'), ('SM', 'Science of Matter'), ('ST', 'Science and Technology'), ('SNV', 'Science of Nature and Life'), ('STU', 'Science of Earth and the Universe'), ('MATH', 'Mathematics'), ('FEI', 'Electric Engineering and Computer Science'), ('PHY', 'Physics'), ('CHI', 'Chemistry'), ('GC', 'Civil Engineering'), ('GM', 'Mechanical Engineering'), ('GP', 'Process Engineering'), ('BIO', 'Biology'), ('EARTH', 'Science of Earth'), ('GAT', 'Geography and Territorial Planning'), ('O', 'Other')], max_length=20)),
                ('level', models.CharField(choices=[('', 'Select Your Level'), ('L1', 'Undergrad. deg. 1'), ('L2', 'Undergrad. deg. 2'), ('L3', 'Undergrad. deg. 3'), ('M1', "Master's deg. 1"), ('M2', "Master's deg. 2"), ('D', 'Doctorate deg.'), ('O', 'Other')], max_length=5)),
                ('experience', models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')])),
                ('do_git', models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')])),
                ('do_fest', models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')])),
                ('conduct', models.BooleanField()),
            ],
        ),
    ]
