# Generated by Django 3.0.8 on 2020-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='do_talk',
            field=models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')], default=False),
            preserve_default=False,
        ),
    ]
