# Generated by Django 3.0.8 on 2020-09-29 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_do_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='git_username',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_user_name', message='This is not a valid first username.', regex='^([a-zA-Z])[a-zA-Z_-]*[\\w_-]*[\\S]$|^([a-zA-Z])[0-9_-]*[\\S]$|^[a-zA-Z]*[\\S]$')]),
        ),
    ]
